import { randomUUID } from 'crypto'
export const growdevers = [
  {
    id: randomUUID(),
    nome: "Roger",
    email: "roger@roger.com",
    idade: 23,
    matriculado: true,
  },
  {
    id: randomUUID(),
    nome: "Clara",
    email: "clara@clara.com",
    idade: 23,
    matriculado: false,
  },
  {
    id: randomUUID(),
    nome: "Luiza",
    email: "luiza@luiza.com",
    idade: 23,
    matriculado: false,
  },
  {
    id: randomUUID(),
    nome: "Daphne",
    email: "daphne@daphne.com",
    idade: 25,
    matriculado: false,
  },
  {
    id: randomUUID(),
    nome: "Sofia",
    email: "sofia@sofia.com",
    idade: 21,
    matriculado: true,
  },
  {
    id: randomUUID(),
    nome: "Alessandro",
    email: "alessandro@alessandro.com",
    idade: 21,
    matriculado: true,
  },
  {
    id: randomUUID(),
    nome: "Regis",
    email: "regis@regis.com",
    idade: 21,
    matriculado: true,
  },
  {
    id: randomUUID(),
    nome: "Maia",
    email: "maia@maia.com",
    idade: 21,
    matriculado: true,
  },
  {
    id: randomUUID(),
    nome: "Ronaldo",
    email: "ronaldo@ronaldo.com",
    idade: 21,
    matriculado: true,
  },
  {
    id: randomUUID(),
    nome: "Marisa",
    email: "marisa@marisa.com",
    idade: 21,
    matriculado: true,
  },
];